#!/usr/bin/env python

# TODO getopt, tokens, ..., C source

import sys
from toe.lexer import TLexer, ELexerEofError
from toe.lexer.compiler import TLexerGenerator, ELexerLoadError
from toe.tokens import TToeToken # TODO

import cStringIO
import pickle


def usage(exit_code = 1):
	print >>sys.stderr, """Usage: %s [-l {pickle|c}] [-t <python-thing-name>] [-o <output-file-name>] <source-rules-file-name>

--target-language={pickle|c}
--tokens=<python-thing-name>
--output=<output-file-name>   # defaults to standard output
<source-rules-file-name>""" % sys.argv[0]
	sys.exit(exit_code)

usage()

generator_stream = file("toe-lexer-symbols.source", "r")

generator = TLexerGenerator(TToeToken)
states = generator.load(generator_stream, False)

f = file("toe-lexer-symbols.compiled", "w")
pickle.dump(states, f)
f.close()

